export const UPLOADS = {
  AVATAR_FIELD: "file",
  AVATAR_FIELD_ALIAS: "avatar",
  MAX_IMAGE_SIZE_BYTES: 2 * 1024 * 1024,
  IMAGE_MIME_PREFIX: "image/",
  PUBLIC_PATH: (filename: string) => `/uploads/${filename}`,
  POC_FIELD: "pocs",
  MAX_POC_FILES: 10,
  MAX_POC_FILE_SIZE_BYTES: 100 * 1024 * 1024,
  MAX_POC_IMAGE_SIZE_BYTES: 10 * 1024 * 1024,
  MAX_POC_DOCUMENT_SIZE_BYTES: 20 * 1024 * 1024,
  MAX_POC_TOTAL_SIZE_BYTES: 250 * 1024 * 1024,
  POC_MIME_TYPES: [
    "image/jpeg", "image/png", "image/webp", "image/gif",
    "video/mp4", "video/webm", "video/quicktime",
    "application/pdf", "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.ms-powerpoint",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "text/plain", "text/csv",
  ],
} as const;
